### PR TITLE
Outline counter

### PR DESCRIPTION
**Pull request by andrewbernard**
Greatly improved new version of outline counter that supports specification of list styles including numeric, alphabetic upper and lower case, and roman numerals, upper and lowercase.

### CODE REVIEW

**Comment by uliska** [comment]
@andrewbernard I've applied a (needed) safeguard against invalid list-style arguments and a (theoretically optional) syntax change for the usage example.

One more wish one could have is a way to apply styling to the numbering (e.g. `\bold` or `\bold italic`). This *could* be done with a `ly:context-mod?` as optional second argument.

**Comment by uliska** [comment]
I thought it even better not to use `for-each` but rather `filter` to filter out invalid keys.
This will probably still expose the follow-up errors but *may* in some cases fix the problem
if only an unused last style is invalid.

**Comment by uliska** [comment]
I had a first look at the implementation of `inc` and decided that *I* won't give a shot at making that configurable. But I would not say this should block the merge. So @andrewbernard please tell me if you'd like to add that feature. Otherwise we can merge the PR.

**Comment by andrewbernard** [comment]
I cant see how the \inc function needs anything else.

Please merge this code.

**Pull request merged**
